version: '3'
services:
  site:
    command: jekyll serve --watch --incremental
    # command: bundle exec jekyll serve
    # command: npm start
    image: jekyll/jekyll:latest
    volumes:
      - ./site:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
